version: "3.7"

services:
    web:
        build: .
        command: sh -c "flask run -p 1337"
        ports:
            - 1337:1337
        depends_on:
            - db
        environment:
            FLASK_APP: shortnr
            FLASK_ENV: development
            SECRET_KEY: 'd950ce0d-98b5-4bba-9cf1-addaa8ba7ba8'
            MONGODB_HOST: localhost
            MONGODB_PORT: '27017'
            MONGODB_USERNAME: dev
            MONGODB_PASSWORD: 7520c7c1
        volumes:
            - .:/usr/src/shortnr
    db:
        image: mongo:4.2.8-bionic
        environment:
            MONGO_INITDB_ROOT_USERNAME: dev
            MONGO_INITDB_ROOT_PASSWORD: 7520c7c1
        ports:
            - 27017:27017
